package jp.co.mbch.dataAccess.entity;

import java.util.Date;

public class Response {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer responseId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer responseNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer threadId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.handle_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String handleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.mail_address
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String mailAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_user_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String responseUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String responseComment;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date createTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date updateTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_id
     * @return  the value of response.response_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getResponseId() {
        return responseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_id
     * @param responseId  the value for response.response_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setResponseId(Integer responseId) {
        this.responseId = responseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_no
     * @return  the value of response.response_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getResponseNo() {
        return responseNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_no
     * @param responseNo  the value for response.response_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setResponseNo(Integer responseNo) {
        this.responseNo = responseNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.thread_id
     * @return  the value of response.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.thread_id
     * @param threadId  the value for response.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.handle_name
     * @return  the value of response.handle_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getHandleName() {
        return handleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.handle_name
     * @param handleName  the value for response.handle_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setHandleName(String handleName) {
        this.handleName = handleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.mail_address
     * @return  the value of response.mail_address
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.mail_address
     * @param mailAddress  the value for response.mail_address
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_user_id
     * @return  the value of response.response_user_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getResponseUserId() {
        return responseUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_user_id
     * @param responseUserId  the value for response.response_user_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setResponseUserId(String responseUserId) {
        this.responseUserId = responseUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_comment
     * @return  the value of response.response_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getResponseComment() {
        return responseComment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_comment
     * @param responseComment  the value for response.response_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setResponseComment(String responseComment) {
        this.responseComment = responseComment;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.create_timestamp
     * @return  the value of response.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.create_timestamp
     * @param createTimestamp  the value for response.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.update_timestamp
     * @return  the value of response.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.update_timestamp
     * @param updateTimestamp  the value for response.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.delete_flag
     * @return  the value of response.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.delete_flag
     * @param deleteFlag  the value for response.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}