package jp.co.mbch.dataAccess.entity;

public class ResponseKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    private Integer responseId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column response.thread_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    private Integer threadId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_id
     * @return  the value of response.response_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    public Integer getResponseId() {
        return responseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_id
     * @param responseId  the value for response.response_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    public void setResponseId(Integer responseId) {
        this.responseId = responseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column response.thread_id
     * @return  the value of response.thread_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column response.thread_id
     * @param threadId  the value for response.thread_id
     * @mbggenerated  Sun May 31 11:18:27 JST 2015
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }
}