package jp.co.mbch.dataAccess.entity;

import java.util.Date;

public class Thread {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer threadId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.thread_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer threadNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer topicId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.thread_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String threadName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer displayIndex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date createTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date updateTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column thread.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.thread_id
     * @return  the value of thread.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.thread_id
     * @param threadId  the value for thread.thread_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.thread_no
     * @return  the value of thread.thread_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getThreadNo() {
        return threadNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.thread_no
     * @param threadNo  the value for thread.thread_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setThreadNo(Integer threadNo) {
        this.threadNo = threadNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.topic_id
     * @return  the value of thread.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.topic_id
     * @param topicId  the value for thread.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.thread_name
     * @return  the value of thread.thread_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.thread_name
     * @param threadName  the value for thread.thread_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setThreadName(String threadName) {
        this.threadName = threadName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.display_index
     * @return  the value of thread.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.display_index
     * @param displayIndex  the value for thread.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDisplayIndex(Integer displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.create_timestamp
     * @return  the value of thread.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.create_timestamp
     * @param createTimestamp  the value for thread.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.update_timestamp
     * @return  the value of thread.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.update_timestamp
     * @param updateTimestamp  the value for thread.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column thread.delete_flag
     * @return  the value of thread.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column thread.delete_flag
     * @param deleteFlag  the value for thread.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}