package jp.co.mbch.dataAccess.entity;

import java.util.Date;

public class TopicType {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic_type.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer topicTypeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic_type.topic_type_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String topicTypeName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic_type.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date createTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic_type.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date updateTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic_type.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic_type.topic_type_id
     * @return  the value of topic_type.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getTopicTypeId() {
        return topicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic_type.topic_type_id
     * @param topicTypeId  the value for topic_type.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicTypeId(Integer topicTypeId) {
        this.topicTypeId = topicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic_type.topic_type_name
     * @return  the value of topic_type.topic_type_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getTopicTypeName() {
        return topicTypeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic_type.topic_type_name
     * @param topicTypeName  the value for topic_type.topic_type_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicTypeName(String topicTypeName) {
        this.topicTypeName = topicTypeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic_type.create_timestamp
     * @return  the value of topic_type.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic_type.create_timestamp
     * @param createTimestamp  the value for topic_type.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic_type.update_timestamp
     * @return  the value of topic_type.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic_type.update_timestamp
     * @param updateTimestamp  the value for topic_type.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic_type.delete_flag
     * @return  the value of topic_type.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic_type.delete_flag
     * @param deleteFlag  the value for topic_type.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}