package jp.co.mbch.dataAccess.entity;

import java.util.Date;

public class Topic {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer topicId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topic_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer topicNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer topicTypeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topic_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String topicName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topic_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private String topicComment;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer displayIndex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date createTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Date updateTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column topic.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topic_id
     * @return  the value of topic.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topic_id
     * @param topicId  the value for topic.topic_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topic_no
     * @return  the value of topic.topic_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getTopicNo() {
        return topicNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topic_no
     * @param topicNo  the value for topic.topic_no
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicNo(Integer topicNo) {
        this.topicNo = topicNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topic_type_id
     * @return  the value of topic.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getTopicTypeId() {
        return topicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topic_type_id
     * @param topicTypeId  the value for topic.topic_type_id
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicTypeId(Integer topicTypeId) {
        this.topicTypeId = topicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topic_name
     * @return  the value of topic.topic_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topic_name
     * @param topicName  the value for topic.topic_name
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topic_comment
     * @return  the value of topic.topic_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public String getTopicComment() {
        return topicComment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topic_comment
     * @param topicComment  the value for topic.topic_comment
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setTopicComment(String topicComment) {
        this.topicComment = topicComment;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.display_index
     * @return  the value of topic.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDisplayIndex() {
        return displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.display_index
     * @param displayIndex  the value for topic.display_index
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDisplayIndex(Integer displayIndex) {
        this.displayIndex = displayIndex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.create_timestamp
     * @return  the value of topic.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.create_timestamp
     * @param createTimestamp  the value for topic.create_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.update_timestamp
     * @return  the value of topic.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.update_timestamp
     * @param updateTimestamp  the value for topic.update_timestamp
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column topic.delete_flag
     * @return  the value of topic.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column topic.delete_flag
     * @param deleteFlag  the value for topic.delete_flag
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}