package jp.co.mbch.dataAccess.client;

import java.util.List;
import jp.co.mbch.dataAccess.entity.Response;
import jp.co.mbch.dataAccess.entity.ResponseExample;
import jp.co.mbch.dataAccess.entity.ResponseKey;
import org.apache.ibatis.annotations.Param;

public interface ResponseMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int countByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByPrimaryKey(Integer responseId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insert(Response record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insertSelective(Response record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    List<Response> selectByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    Response selectByPrimaryKey(Integer responseId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExampleSelective(@Param("record") Response record, @Param("example") ResponseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExample(@Param("record") Response record, @Param("example") ResponseExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKeySelective(Response record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table response
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKey(Response record);
}