package jp.co.mbch.dataAccess.client;

import java.util.List;

import jp.co.mbch.dataAccess.entity.Thread;
import jp.co.mbch.dataAccess.entity.ThreadExample;

import org.apache.ibatis.annotations.Param;

public interface ThreadMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int countByExample(ThreadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByExample(ThreadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByPrimaryKey(Integer threadId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insert(Thread record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insertSelective(Thread record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    List<Thread> selectByExample(ThreadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    Thread selectByPrimaryKey(Integer threadId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExampleSelective(@Param("record") Thread record, @Param("example") ThreadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExample(@Param("record") Thread record, @Param("example") ThreadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKeySelective(Thread record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table thread
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKey(Thread record);
}