package jp.co.mbch.dataAccess.client;

import java.util.List;
import jp.co.mbch.dataAccess.entity.TopicType;
import jp.co.mbch.dataAccess.entity.TopicTypeExample;
import org.apache.ibatis.annotations.Param;

public interface TopicTypeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int countByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByPrimaryKey(Integer topicTypeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insert(TopicType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insertSelective(TopicType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    List<TopicType> selectByExample(TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    TopicType selectByPrimaryKey(Integer topicTypeId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExampleSelective(@Param("record") TopicType record, @Param("example") TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExample(@Param("record") TopicType record, @Param("example") TopicTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKeySelective(TopicType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic_type
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKey(TopicType record);
}