package jp.co.mbch.dataAccess.client;

import java.util.List;
import jp.co.mbch.dataAccess.entity.Topic;
import jp.co.mbch.dataAccess.entity.TopicExample;
import org.apache.ibatis.annotations.Param;

public interface TopicMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int deleteByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    Topic selectByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table topic
     * @mbggenerated  Sun May 31 14:27:27 JST 2015
     */
    int updateByPrimaryKey(Topic record);
}